name: Check PR Source Branch

on:
  pull_request_target:
    types: [opened, reopened, synchronize, edited]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    if: github.base_ref == 'master'
    steps:
      - name: Check source branch
        run: |
          if [ "${{ github.head_ref }}" != "develop" ]; then
            echo "ERROR: Pull requests to master are only allowed from the 'develop' branch."
            exit 1
          fi
          echo "Source branch is 'develop' - approved!"
